name: Check for broken links on site

on:
  workflow_run:
    workflows: [Deploy site]
    types: [completed]

jobs:
  check-links-on-site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download built site 📦
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: >
            --offline
            --verbose
            --no-progress
            _site/**/*.html
