name: Check for broken links on site
on:
  workflow_run:
    workflows: [Deploy site]
    types: [completed]
jobs:
  check-links-on-site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }}
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Install Node (for purgecss if needed) 📦
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies 🔧
        run: |
          pip3 install --upgrade jupyter
          bundle install
      - name: Copy file from subrepo to main repo 📂
        run: |
          cp _cv/output/cv_eng.pdf assets/pdf/
          cp ntu_exchange/me.pdf assets/img/
          cp ntu_exchange/travel_report.pdf assets/pdf/
          cp ntu_exchange/title_fig.pdf assets/img/
          cp ntu_exchange/ntu_courses/PH3406/density_matrix_meas.pdf assets/img/
          cp ntu_exchange/ntu_courses/PH3406/ph3406_project_OS.pdf assets/pdf/
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ghostscript librsvg2-bin
      - name: Build Jekyll site 🏗️
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Purge unused CSS 🧹
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: >
            --offline
            --remap '_site(/?.*)/assets/(.*) _site/assets/$2'
            --exclude-path '.*\.webp'
            --verbose
            --no-progress
            '_site/**/*.html'
